### ISSUE TITLE
Unable to play video (BadImageFormatException)

### ISSUE THREAD

**Issue by MinChanSike** [rockcarry/fanplayer#12]
Hi author, thanks for your share.
I try build **funplayer** on VS2017 and play video file, 
but got error message on `PlayerForm_Load `-> ` player_open`.

`System.BadImageFormatException: 'An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)'`

I do configure to build **funplayer** project follow by your [instruction](https://github.com/rockcarry/fanplayer/wiki/build-fanplayer#got-compile-error-).

> Add #define _TIMESPEC_DEFINED

> Set No (/SAFESEH:NO)

**csharpplayer** project is only need one dll dependency right? 
![file_dependency](https://user-images.githubusercontent.com/2868221/57771744-38733080-7746-11e9-8919-1b937452a027.png)

Thank you in advance

**Comment by rockcarry** [comment]
lastest version v1.9.0 now support vs2017 vs2019
you can have a test.
