### ISSUE TITLE
HwAccel does not work

### ISSUE THREAD

**Issue by doubleaa93** [rockcarry/fanplayer#13]
It looks like render-dev is NULL when this line gets called
render_getparam(player->render, PARAM_VDEV_GET_D3DDEV, &d3ddev);

so hw accel never works

**Comment by rockcarry** [comment]
should setup init params:
video_hwaccel      = 1;
vdev_render_type   = 1;

**Comment by befovy** [comment]
Windows 10 device.
After set params 
```
video_hwaccel = 1;
vdev_render_type = 1;
```

But It still looks like render-dev is NULL when this line gets called
render_getparam(player->render, PARAM_VDEV_GET_D3DDEV, &d3ddev);

**Comment by rockcarry** [comment]
I build a new verion, please help me to test it for hwaccel, on win7 & win10.

**Comment by LittleKu** [comment]
朋友，貌似硬解码不支持，如楼上提的，在render_getparam(player->render, PARAM_VDEV_GET_D3DDEV, &d3ddev);之前还没有创建d3d的设备，似乎要把创建d3d设备提前才行

**Comment by rockcarry** [comment]
@all
I pushed new code fixing the HwAccel does not work issue.
tag v1.6.8
please check and test.
