### ISSUE TITLE
arm-linux-androideabi-gcc is unable to create an executable file.

### ISSUE THREAD

**Issue by gevariya-ajit** [rockcarry/fanplayer#2]
Error at the time of building `./build_ffmpeg_for_android.sh`

> /toolchains/arm-linux-androideabi-4.9/prebuilt/windows/bin/arm-linux-androideabi-gcc is unable to create an executable file.
> C compiler test failed.

NDK 16.1.447

**Comment by gevariya-ajit** [comment]
After fixing `EXTRA_LDFLAGS="/usr/local/include"`

>  /ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-gcc is unable to create an executable file.
>  C
> 
>  compiler test failed.

**Comment by rockcarry** [comment]
there is no need to build x264
edit the build_ffmpeg_for_android.sh file, remove lines:
--enable-encoder=libx264 \
--enable-libx264 \
and try.

x264 is used for encoding. if you want to compile it, try

change

#++ build x264 ++#
if false; then
if [ ! -d x264 ]; then

if false; then   -> if true; then

**Comment by gevariya-ajit** [comment]
@rockcarry Even though gcc is not building with latest NDK, If you can help to build with **clang**?

**Comment by rockcarry** [comment]
I am sorry, I don't have the ios build enviroment.

**Comment by gevariya-ajit** [comment]
It's about android.

Here are some prebuild though. https://sourceforge.net/projects/avbuild/files/android/

**Comment by rockcarry** [comment]
in my project, ffmpeg library files already build and put into player-android/ffmpeg-android directory.
you can use it directly.

**Comment by rockcarry** [comment]
I can build successfuly, enviroment is:

windows xp / windows 7
msys2
android-ndk-r13b

**Comment by rockcarry** [comment]
you can try to build in this enviroment

**Comment by gevariya-ajit** [comment]
Ah sorry i have only Mac available here. But thanks for your help. I am trying to use .so files from above link.

**Comment by rockcarry** [comment]
ok.

fanplayer project dose not using the ffmpeg shared library, but using the static .a library. all of the ffmpeg .a library compiled with fanplayer .c files and linked into libfanplayer_jni.so.

**Comment by gevariya-ajit** [comment]
Yup got it!

Thanks for your time :)
