### ISSUE TITLE
why dxva dosn't work?

### ISSUE THREAD

**Issue by zslovelq** [rockcarry/fanplayer#20]
I play a local mp4 video. it only works on CPU,but not GPU.
I want to use GPU to play.

**Comment by rockcarry** [comment]
make sure player parameters set to:
vdev_render_type = 1;
video_hwaccel    = 1;

**Comment by zslovelq** [comment]
Thank you! GPU works.
But CPU occupancy is still high.

**Comment by zslovelq** [comment]
看代码大神是中国人啊。
现在的问题是虽然任务管理器能看到GPU工作了，但是CPU使用率没有降低。
播放720P视频，不管开不开GPU解码，CPU的使用率一直是15-20%.
求解释。我想做个16路视频监控软件，这么高的CPU占用肯定不行。

**Comment by rockcarry** [comment]
别人测试结果比你的好，基本上 1% 左右的使用率。
用了多少电脑测试过，MP4 是 h264、还是 h265，多换几个视频文件测试看下结果。

**Comment by zslovelq** [comment]
现在没问题了，我下载了你的binary版本的，里面有配置文件。
可能是我配置文件配置项没配全的原因。
现在CPU低于1%了。

**Comment by rockcarry** [comment]
ok, this issue can be closed.

**Comment by zslovelq** [comment]
Thank you!
