### ISSUE TITLE
播放1080P rtsp视频，底部有黑条

### ISSUE THREAD

**Issue by zslovelq** [rockcarry/fanplayer#21]
摄像头是海康的，视频编码是H264. 地址rtsp://admin:ferret123@192.168.8.79:554/h264/ch1/main/av_stream
播放低清的没发现底部有黑色条。
用其他软件录制好1080P视频流成MP4，再用fanplayer打开就正常。

黑条具体表现为1920*1080的视频长宽比改变成1920*900，相当于视频被压扁了一点点，下面有个1920*180的黑色条状。 
900是大概数字，具体不知道是多少。这个评论没法发图片给你看。

**Comment by zslovelq** [comment]
测试软解1080P视频流没问题，只有硬解才有黑条，这个大神能测试一下，解决bug吗？

**Comment by rockcarry** [comment]
video_hwaccel      = 0;
vdev_render_type   = 1;
测下这个配置的播放结果

**Comment by zslovelq** [comment]
video_hwaccel = 0;之后，GPU占用会上去，CPU也没降低，达不到硬解的效果。
我刚又测试了，虽然链接地址是h264，但实际用的是H265编码。把摄像头参数调整成H264硬解就正常了。
这个不支持H265 流媒体硬解吗？

**Comment by zslovelq** [comment]
刚才又试了一下播放第三码流，不管分辨率调成多少，只要是H265格式，一定会带黑条。VLC播放器不会。

**Comment by rockcarry** [comment]
video_hwaccel = 0;
vdev_render_type = 1;
测下这个配置的播放结果，这个结果又了吗？
是不是 h264 和 h265 都是 ok 的，只是 CPU 占用高？

**Comment by zslovelq** [comment]
是正常的，但是我不想CPU占用高，因为要多路视频播放，CPU高了不行。

**Comment by zslovelq** [comment]
大神能解决一下h265视频流的bug吗？

**Comment by rockcarry** [comment]
总结说就是 h265 + 硬件加速，显示就不正常对吧。

**Comment by zslovelq** [comment]
是的

**Comment by zslovelq** [comment]
总结说就是H265+硬解加速+RTSP，就多个黑条。
本地视频是没问题的。

**Comment by rockcarry** [comment]
那这个很奇怪了，为啥本地视频是正常的？
control+w 看下。

**Comment by zslovelq** [comment]
没效果，还是有黑条。你可以自己找个海康的摄像头试试H265就知道了。

**Comment by zslovelq** [comment]
https://github.com/Yacov-lu/ffmpeg-DXVA-decode参考这个工程的源码
	RECT SourceRect = { 0,0,((~0 - 1)&frame->width),((~0 - 1)&frame->height) };
	ctx->d3d9device->StretchRect(surface, &SourceRect, m_pBackBuffer, NULL, D3DTEXF_LINEAR);
对应fanplayer源码
        IDirect3DDevice9_StretchRect(c->pD3DDev, surf, NULL, c->bkbuf, NULL, D3DTEXF_LINEAR);
区别是他的有SourceRect,你的是NULL。
说一下我的测试方法：
1.他的代码注释掉SourceRect，也显示底部有黑条，不注释显示正常
2.你的代码的NULL换成视频的rect之后，显示黑屏，不知道原因。
如果你不改掉这个bug,我只能用他的代码了，他的代码比较原始，功能少，也没线程优化。我用起来会改动比较大。

**Comment by rockcarry** [comment]
我和没有调试环境。感觉是 d3d surface 在 copy 的时候出问题了。
你试下旋转显示是否正常，用 ctrl+X 命令。

**Comment by zslovelq** [comment]
//if ((c->textt[0] || (c->status & VDEV_D3D_DXVA2)) && c->surfw) {
    //    IDirect3DDevice9_StretchRect(c->pD3DDev, surf, &SourceRect, c->surfw, NULL, D3DTEXF_LINEAR);

    //    if (c->status & VDEV_CONFIG_FONT) {
    //        c->status &= ~VDEV_CONFIG_FONT;
    //        logfont.lfHeight = c->font_size;
    //        _tcscpy_s(logfont.lfFaceName, _countof(logfont.lfFaceName), c->font_name);
    //        if (c->hfont) DeleteObject(c->hfont);
    //        c->hfont = CreateFontIndirect(&logfont);
    //    }

    //    IDirect3DSurface9_GetDC(c->surfw, &hdc);
    //    SelectObject(hdc, c->hfont);
    //    SetTextColor(hdc, c->textc);
    //    SetBkMode   (hdc, TRANSPARENT);
    //    TextOut(hdc, c->textx, c->texty, c->textt, (int)_tcslen(c->textt));
    //    IDirect3DSurface9_ReleaseDC(c->surfw, hdc);

    //    surf = c->surfw;
    //}
    IDirect3DDevice9_StretchRect(c->pD3DDev, surf, &SourceRect, c->bkbuf, NULL, D3DTEXF_LINEAR);
    IDirect3DDevice9_Present(c->pD3DDev, NULL, &rect, NULL, NULL);
跟旋转没关系，跟文字显示有关，我把显示文字的代码注释掉，并且IDirect3DDevice9_StretchRect加上SourceRect，就没有黑条了。反正我对文字显示没有需求，这段代码完全可以注释。不过你可以尝试解决一下。
不仅仅是没有黑条了，清晰度也明显提升。

**Comment by zslovelq** [comment]
if ((c->textt[0] || (c->status & VDEV_D3D_DXVA2)) && c->surfw) {
		IDirect3DDevice9_StretchRect(c->pD3DDev, surf, NULL, c->surfw, NULL, D3DTEXF_LINEAR);

		if (c->status & VDEV_CONFIG_FONT) {
			c->status &= ~VDEV_CONFIG_FONT;
			logfont.lfHeight = c->font_size;
			_tcscpy_s(logfont.lfFaceName, _countof(logfont.lfFaceName), c->font_name);
			if (c->hfont) DeleteObject(c->hfont);
			c->hfont = CreateFontIndirect(&logfont);
		}

		IDirect3DSurface9_GetDC(c->surfw, &hdc);
		SelectObject(hdc, c->hfont);
		SetTextColor(hdc, c->textc);
		SetBkMode(hdc, TRANSPARENT);
		TextOut(hdc, c->textx, c->texty, c->textt, (int)_tcslen(c->textt));
		IDirect3DSurface9_ReleaseDC(c->surfw, hdc);

		surf = c->surfw;
	}
    IDirect3DDevice9_StretchRect(c->pD3DDev, surf, NULL, c->bkbuf, NULL, D3DTEXF_LINEAR);
    IDirect3DDevice9_Present(c->pD3DDev, NULL, &rect, NULL, NULL);
这个是你的源码
