### ISSUE TITLE
render_video的用途是什么？

### ISSUE THREAD

**Issue by vzhilong** [rockcarry/fanplayer#22]
阅读代码到video_decode_thread_proc中，packet == null时调用render_video的意图不太理解，render_audio已经被注释了，render_video注释后好像也没有副作用。

**Comment by vzhilong** [comment]
我现在的理解大致是显示上一帧内容，不知道理解的对不对。虽然我测试的过程中注释了这一段好像也没啥影响。

**Comment by rockcarry** [comment]
你试下暂停播放，然后再隐藏窗口看看
