### ISSUE TITLE
此工程ffmpeg 版本是多少？

### ISSUE THREAD

**Issue by wangpeng1** [rockcarry/fanplayer#25]
您好，此工程的ffmpeg版本是多少，目前的ffmpeg 都不支持flv封装H265，我已经写好兼容。但是对于播放不是很清楚，想在你的工程中修改，但是通过替换ffmpeg 库的形式，ffplay找不到想要的方法。所以想知道你的ffmpeg的方法，或者能否进一步沟通

**Comment by rockcarry** [comment]
https://github.com/rockcarry/ffmpeg
用这个仓库和对应的分支

**Comment by rockcarry** [comment]
fanplayer-n3.3.x 分支

**Comment by rockcarry** [comment]
this issue can be closed.

**Comment by flyboyxiang** [comment]
ffmpeg版本可以更新到4点几吗
