### ISSUE TITLE
能否支持本地的 播放的进度和时长？

### ISSUE THREAD

**Issue by wangpeng1** [rockcarry/fanplayer#26]

**Comment by rockcarry** [comment]
支持

**Comment by wangpeng1** [comment]
我用的是Android 版，没有看见调用的方法获取当前时间和总长度，能说一下哪个方法吗？

**Comment by wangpeng1** [comment]
player->avformat_context->duration 此方法吗

**Comment by rockcarry** [comment]
public static final int PARAM_MEDIA_DURATION    = 0x1000 + 0;
    public static final int PARAM_MEDIA_POSITION    = 0x1000 + 1;
    public static final int PARAM_VIDEO_WIDTH       = 0x1000 + 2;
    public static final int PARAM_VIDEO_HEIGHT      = 0x1000 + 3;    public long getParam(int id)             { return nativeGetParam(m_hPlayer, id); }

**Comment by rockcarry** [comment]
this issue can be closed.
