### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [rockcarry/fanplayer#3]
Hello Sir. I'm a UI/UX and Graphics Designer. I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by rockcarry** [comment]
That's greate.

Thank you. and when can you complete you design.

**Comment by anharismail** [comment]
I'll design my logo proposal as soon as possible

**Comment by anharismail** [comment]
Hello, Sir @rockcarry . These are my logo proposal for your project.
I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.
I'll provide all file types and sizes you needed.
Hope you like it.

### Version 1
![fanplayer ver 1](https://user-images.githubusercontent.com/37614260/40652414-654cbe26-6362-11e8-8af1-a9fcf9ad05ef.png)

### Version 2
![fanplayer ver 2](https://user-images.githubusercontent.com/37614260/40652423-6cc13c68-6362-11e8-8337-26a5e53e51eb.png)

**Comment by rockcarry** [comment]
thanks a lot, it both looks very good.

**Comment by rockcarry** [comment]
I like the version 2.

**Comment by rockcarry** [comment]
please help me, give me the png file, and cut the full and small  logo into separate ones.
I will put the logo on the fanplayer github website.

and then I will use the logo for fanplayer app icon for both win32 and android.
for app I need different size png icon,  I will tell you what I need, when I work on changing the app icons.

thanks a lot.

**Comment by anharismail** [comment]
Hello Sir @rockcarry , Thank you so much for your appreation to using my logo proposal :)

Here I provide all the files you needed; https://drive.google.com/drive/u/1/folders/1g3236DGThA27CEllPlEue6svFE1BFqX1

One more, could you merged it on your repositories?

**Comment by rockcarry** [comment]
I put the logo file to my git repo.

but the picture size is to large.

you can visit this link to check:
https://github.com/rockcarry/fanplayer

I don't have picture edit tools on my hard, so need your help.

**Comment by rockcarry** [comment]
may I know your email address ?
I want to send some app icon requirement which needed by fanplayer to you.

**Comment by anharismail** [comment]
Hello, Sir. You can sent it to anharismailsyah@gmail.com

**Comment by anharismail** [comment]
Hello @rockcarry , I've provided all favicon you needed for fanplayer. I also added small logo fit for your readme repository. Please, check your email.

I've updated the logo folder for this repository too. Check here: https://drive.google.com/drive/u/1/folders/1g3236DGThA27CEllPlEue6svFE1BFqX1

Anyway, could you merged my pull request? Thanks before :)

**Comment by rockcarry** [comment]
would you please re-send your pull request ?

I tried to merge your pull request bug got problem. and the pull request has been closed.

:-(

**Comment by anharismail** [comment]
@rockcarry , I've done pulling a request again :smile:

**Comment by anharismail** [comment]
Oh I mean just merged my post about logo presentation, because there are logo files on the post. 

Anyway, what kind of post u mean? Is just the file?

**Comment by rockcarry** [comment]
It doesn't seem to be good.

as I know, (even though I haven't send pull request to other yet),  you need do as follow:
1. fork the repo of fanplayer
2. create a new branch, example _add-project-logo_
3. on the new branch, you can modify the files of fanplayer project
4. add and commit all the changes to the new branch
5. push the branch  to your own git repo 
6. then send the pull request to me

on your new branch, you can add the logo file to project, and change the readme.md to make the logo display, or do something else...

It is a little complex to do it. you can readme some document of howto send pull request.

**Comment by rockcarry** [comment]
and I find a problem of logo picture file. in the png picture files, the big letter F is tranparent. It looks strange if the background is not white. do you know what I mean ?

**Comment by anharismail** [comment]
Okay, I'll try do the steps you suggested.

Yes, the F must be transparent, it makes the logo looks professional and proporsional.  The logo can put on light background. If there's any case on dark bacground, you can put the white logo. That's why I make it many versions :)

**Comment by rockcarry** [comment]
I successfully merged you new pull request.

I sugguest rename directory name “logo fanplayer” to "logo", and I sugguest you modify the readme.md file. the first line is the logo code.

thank you.

**Comment by rockcarry** [comment]
I think we'd better delete the fanplayer.png in the root dir of project.

**Comment by rockcarry** [comment]
and you can also replace the app icon files, the file path is:

fanplayer\player-win32\testplayer\res\player.ico
fanplayer\player-android\apk\app\src\main\res\drawable-ldpi\ic_launcher.png
fanplayer\player-android\apk\app\src\main\res\drawable-mdpi\ic_launcher.png
fanplayer\player-android\apk\app\src\main\res\drawable-hdpi\ic_launcher.png
fanplayer\player-android\apk\app\src\main\res\drawable-xhdpi\ic_launcher.png

**Comment by anharismail** [comment]
Hi @rockcarry , I'm using GitHub web, it's very difficult for me to update the repository and there are so many problem happened when I trying to pull a request.

Do you mind to help me update your repositories by yourself? I've provided all the files you needed on this link https://drive.google.com/drive/u/1/folders/1g3236DGThA27CEllPlEue6svFE1BFqX1 and email attachment I've sent. In this link include the logo fit for the readme. Hope you understand :)

**Comment by rockcarry** [comment]
ok

**Comment by anharismail** [comment]
Hi @rockcarry , I've create the better quality icon for you. Please, download here: https://drive.google.com/drive/u/1/folders/1R9GXnqgJLBvI88yhRYCmMA2HgWGEtbG7

I think this website will help you to provide icon as much and as fast you needed http://icoconvert.com/

Nice to help you again :)

**Comment by rockcarry** [comment]
can you send email to me. I am in China, can't access google server now.
and the http://icoconvert.com/ also can't be open.

**Comment by anharismail** [comment]
Can you acces dropbox? 

I will sent it to your email

**Comment by anharismail** [comment]
Hi @rockcarry , Here all files on Dropbox

https://www.dropbox.com/sh/bej1ix4x0d7216e/AAC-fiUQwCkjwJVOeI3RXe0Fa?dl=0

**Comment by rockcarry** [comment]
I received you mail.

thank you very much.

and I find a website can convert png to ico

http://www.bitbug.net/
