### ISSUE TITLE
支持网络视频实时播放吗？

### ISSUE THREAD

**Issue by haifenghuang** [rockcarry/fanplayer#37]
正如标题所说的，`fanplayer`支持网络视频实时播放吗？
例如，有一个网络MP4文件`https://file-examples-com.github.io/uploads/2017/04/file_example_MP4_480_1_5MG.mp4`,能否使用
`fanplayer`直接播放，而不需要先下载这个mp4文件？

**Comment by rockcarry** [comment]
http 可以支持，https 需要重新编译 ffmpeg 库增加 openssl 就可以了。

**Comment by rockcarry** [comment]
用最新版本在 win7 上实测，可以播放你给的 https 链接

**Comment by haifenghuang** [comment]
多谢！
