### ISSUE TITLE
Available for hire ?

### ISSUE THREAD

**Issue by footballs** [rockcarry/fanplayer#38]
Respected @rockcarry ,
----Do you **accept** working on personal **projects** ? 
----I will pay in **bitcoin**. Half amount would be in advance. And half would be given after work.
----The **project** is based on little **modification** of **fanplayer**.
I am waiting for your reply...

**Comment by footballs** [comment]
offer still remains

**Comment by rockcarry** [comment]
sorry recently I am really very busy.

**Comment by footballs** [comment]
No problem. I understand.
If you have **time** then project is awaiting for you. If it **interests** you then I may add more **details**.
But if you don't, Obviously, I will have to do myself.

There are some **LICENSE** restrictions for commercialism which I want to be get dissolved.
According to that "**you should distribute the modification and changes made in Fan Player.**".
**Commercial** apps are never **open source** to prevent from crackers, competitors etc.
So I can't distribute the changes made in **Fan Player.** 
But I will **credit** and give back-link in **about** and **license** section.
Do you have agreement for **commercial** use ? I will pay from **app profit**.

Before **Fan Player** I was using **[Libvlc](https://www.videolan.org/vlc/libvlc.html)**.
But its **file size** is so much. (around 130mb for each bit).
But I don't know whether  **Fan Player** will meet my needs as **libvlc** did.
Both are based on **ffmpeg**. So I hope for best.
Regards.

**Comment by rockcarry** [comment]
for the LICENSE issue, fanplayer using the LGPLv3, it means you can use it as a share library without open source your code.
and if you modified source code of fanplayer, you need only open source the code of fanplayer that you modified, no need to open source all of you project code.

**Comment by rockcarry** [comment]
if the LGPLv3 LICENSE is not meet your commercial use. it's good for me if you can credit and give back-link in about and license section.

**Comment by footballs** [comment]
>if you modified source code of fanplayer, you need only open source the code of fanplayer.

Do you know **courses** ? (Teachers teaches using videos like [here](https://www.udemy.com/)) Our software is based on prevention of **illegal media distribution**. For this purpose, our media would be encrypted and decrypt in memory and feed to **Fan-Player**.

So if I provide **Fan-Player** modified code, then it will endanger media protection.(anyone could see & modify code to drop decrypted premium media content to a file and leak it).

>  if the LGPLv3 LICENSE is not meet your commercial use. it's good for me if you can credit and give back-link in about and license section.

Not just credits, I will also sponsor this **project** with some % percent of profit. 

But this all depends on **Fan-Player**. There are some functionalities need to be added.
I will pay in advance to modify code. For each little task you will receive 10$. 
If you agree and willing to do then I can include details of these tasks.

**Comment by rockcarry** [comment]
That's good, and I want to know the detail of tasks, to estimate the workload.

**Comment by footballs** [comment]
## Add support for **ifstream** constructor
Currently, we can feed media from either **File Path** or **URL**. pseudo code:
```cpp
void* player_open(char *file, void *win, PLAYER_INIT_PARAMS *params)

//and then we call it like
m_ffPlayer = player_open(m_strUrl, GetSafeHwnd(), params);
```
So we want to add **support** for **stream** as well. pseudo code:
```cpp
#include <fstream>
void* player_open(iftream *stream, void *win, PLAYER_INIT_PARAMS *params)

//and then we would call it like
ifstream Filestream;
m_ffPlayer = player_open(Filestream, GetSafeHwnd(), params);
```

## Add demo for encrypted stream 
In **libvlc**, I have experience, when you decrypt an **encrypted stream** and pass it to **libvlc**, it don't plays because its **unseekable**(github.com/videolan/libvlcsharp/pull/129). So you have to make **seekable** encrypted stream which can play media as usual.
For **demo** you can take any video, encrypt it and decrypt while streaming with any encryption you like.

**budget**:20$
**time**:2 weeks 

Give me your **bitcoin address**. You will receive **10$** for now. After receiving you can start to work on these tasks.
And **10$** after I **receive** source code.
You have to submit modified source code by my email : **mir.imran.khan999@gmail.com**
If you want you can just provide **modified** files not whole **source code**.(for your ease)
These 2 task are important. If you can make it work then **I will move to next tasks**.

If anything unclear or missing, feel free to ask it.

**Comment by footballs** [comment]
See how **libvlc** handle stream and provide it to ffmpeg
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__media.html#ga591c3cbe56444f1949165b2b9b75d8e2
https://stackoverflow.com/a/65112864/11390822
https://github.com/videolan/vlc/blob/235b7212bd0d98a46ae46711479aeb426fd5ce35/lib/media.c#L576
https://github.com/videolan/vlc/blob/6416ea5448a9c16f3449b1c695acda5a356ce240/NEWS#L982
https://github.com/footballs/libvlc_stream_sample

**Comment by rockcarry** [comment]
I have finish code of task: Add support for ifstream constructor.
and test it works fine.

**Comment by rockcarry** [comment]
I suggest you create a private git repository, then I can push the code to you.

**Comment by footballs** [comment]
Ho ! Great
Go ahead and **merge** it 
https://github.com/footballs/fanplayer-stream

Also give me your **bitcoin address** so that I may fulfill my **promise**.
Or create **account** here if you don't have **wallet** : https://www.blockchain.com

**Comment by rockcarry** [comment]
bitcoin address: 1BJ9xfhDJogiajuo9DXE2FJdRr7SmN4VZk

**Comment by rockcarry** [comment]
ifstream branch pushed to your repository.

**Comment by footballs** [comment]
Sent $20. I **tested** player and was working **great**.
For my **clarification**, it plays ifstream in **memory** and **chunk by chunk** without dropping anywhere, Right ?
  
Let's move to next task,
Make a demo that uses **AES-256 encrypted file** and open as **stream** and **decrypt** its and plays it.
Remember stream should be **seekable**. Else it won't play.
https://github.com/videolan/libvlcsharp/pull/129
https://github.com/ZeBobo5/Vlc.DotNet/issues/647

**Comment by rockcarry** [comment]
How about the budget of next task: open and play AES-256 encrypted file ?

**Comment by footballs** [comment]
I was sent $20. 
$10 for ifstream
$10 advance for AES-256 encrypted file
But it hard to tell whether budget is correct or not. 
Feel free to change it according to heavy work you think.

https://www.blockchain.com/btc/tx/9630c6c027f556ac2efa448a55a794f2f9ed56273588c1d796cb6c67fb17fdcc
And remember btc prices are unpredictable. Currently these are arising but not sure about next day. So my advice would be cash it out fast.

**Comment by rockcarry** [comment]
I implemented the AES-256 decryption for ifstream.
please check and test the latest code.

**Comment by footballs** [comment]
@rockcarry 
First of all thanks for the great work,
I read your code.

I encrypted the 750 kb video file i.e input.dat to output.dat
And opened the output.dat with testplayer.
It plays video well.

But there were some minor problems that I faced and will address here:
1) it takes 10--15 seconds to start playing video
2) player stucks and crash sometimes, mostly when seeking (**Player has stopped working**)
3) it starts open file dialog in mid of video.

I will extend budget as per your hard work.

**Comment by rockcarry** [comment]
currently the aes decryption performance is not good. so it takes long time to open a encrypted video.
I'll use openssl library instead to improve the performance.

**Comment by rockcarry** [comment]
I am working on port openssl to fanplayer, and using it instead of aes256.c
I am sure using openssl can have good performace, because it uses the SSE to optimize.
but this will take me long time to port, and also I need change code of avioifs.
so for me, more budget is required, I think 10$ is OK.

**Comment by footballs** [comment]
Sent $10
https://www.blockchain.com/btc/tx/12ce1f42354d08aab4ce7249d123552f585e922e8cd4af2175e4dd2f25fb6a17

Its known issue that seeking remain slow in encrypted stream.
They tells why video is slow in seeking:
https://github.com/google/ExoPlayer/issues/2467
http://blog.moagrius.com/android/android-play-encrypted-video-in-exoplayer/

I have been using AES-256 as it was known to me. 
But use any encryption according to you think which is secure and optimized.

**Comment by rockcarry** [comment]
I pushed latest code, please check.
after using openssl the decrypt performance is good now.

**Comment by footballs** [comment]
Friend, Did you added any function on how to encrypt with this openssl encryption?
I didn't found.

**Comment by rockcarry** [comment]
I'll comment on your repository.
and how about the test result ?

**Comment by rockcarry** [comment]
I comment on my commits pls check.

**Comment by footballs** [comment]
https://github.com/footballs/fanplayer-stream/commit/6e3ce790dee2886ebaa0460b04dfb2aa01530aa6#diff-089d9074e3d5bccadfeb20cd180bb978643111f9a6b6b2648dfacb8531eb1cbeL350-L432

Please add lines like that you added before in aes256.c in openssl encryption as well which encrypts a file.
So that I can easily encrypt an video and test it.
I am having little trouble to understand how do I encrypt. 
And thanks so much for such work.🥰🥰🥰

**Comment by rockcarry** [comment]
> [footballs/fanplayer-stream@6e3ce79#diff-089d9074e3d5bccadfeb20cd180bb978643111f9a6b6b2648dfacb8531eb1cbeL350-L432](https://github.com/footballs/fanplayer-stream/commit/6e3ce790dee2886ebaa0460b04dfb2aa01530aa6#diff-089d9074e3d5bccadfeb20cd180bb978643111f9a6b6b2648dfacb8531eb1cbeL350-L432)
> 
> [footballs/fanplayer-stream@6e3ce79#r45172367](https://github.com/footballs/fanplayer-stream/commit/6e3ce790dee2886ebaa0460b04dfb2aa01530aa6#r45172367)
> Please add lines like that you added before in aes256.c in openssl encryption as well which encrypts a file.
> So that I can easily encrypt an video and test it.
> I am having little trouble to understand how do I encrypt.
> And thanks so much for such work.🥰🥰🥰

you can use old aes256.c test program to do encryption. the only problem is speed is slow.

**Comment by footballs** [comment]
Oh that's mean I can use old aes256 to encrypt. Thats great.
No problem for performance , I don't need performance for encryption. 
Thanks I will try and let you know.

**Comment by footballs** [comment]
brother, I tested it.
Amazingly it improved the performance but still need to more improve.
filesize:10 mb -> memory:20-31 mb , seeking:good 
filesize:120 mb -> memory:172 mb,  seeking:bad(takes 7--15 seconds) 

Go ahead and do it. I will fund more.
I know you can optimize it more.

**Comment by rockcarry** [comment]
not easy.
for AES decryption, using openssl is already the ultimate limit optimization.
and for ifstream reading and seeking, also there is no possible for more optimization.

the seek speed is also depending on different video file type. what type are you using for test?

**Comment by footballs** [comment]
Sorry for **inconvenience**.
You were right that video file was faulty. Even that file takes 300--400 mb memory on vlc and wmp.
And fan player takes 170 mb memory even on encrypted video. Cool and impressive performance. 

Here's information about faulty mp4 video file
```cmd
C:\ffmpeg\bin>ffprobe input.dat
ffprobe version 4.3.1 Copyright (c) 2007-2020 the FFmpeg developers
  built with gcc 10.2.1 (GCC) 20200726
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enab
le-libvidstab --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libgsm --disable-w32threads --enable-libmfx --enable-ffnvcodec --enable-cuda-llvm --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'input.dat':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf57.83.100
  Duration: 00:00:28.24, start: 0.000000, bitrate: 37573 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p, 3840x2160, 37570 kb/s, 23.98 fps, 23.98 tbr, 24k tbn, 47.95 tbc (default)
    Metadata:
      handler_name    : VideoHandler
```

Now its ready. But I have some questions.
Q1) How many **encodings** does this version of **ffmpeg** supports  (i.e avcodec-57) ?
Q2) [Fanplayer-Binary](https://github.com/rockcarry/fanplayer-binary) filesize was impressive. How do you lower down its size ?
Q3) How many windows and android versions supported by fanplayer (e.g win 7 --x and Android 5--X etc) ?
Q4) Is possible make dynamic-link-library compatible both with x86 and x64 bit Operating systems ?

I will close this issue and reward $10 after getting answers.
I am pretty **happy** from your **work**. I have will to hire you in future projects as well.
I don't have number so I can't register on qq. Do you use any other chat app ? (e.g facebook, discord, linkedin etc).

**Comment by rockcarry** [comment]
Q1) How many encodings does this version of ffmpeg supports (i.e avcodec-57) ?
use command:
cd fanplayer\player-win32\ffmpeg\bin
ffmpeg -decoders (or -encoders)
you can see the supported decoders or encoders


Q2) Fanplayer-Binary filesize was impressive. How do you lower down its size ?
binary file can be small, because fanplayer does denpend on too many third party libraries, only ffmpeg, sound touch, pthread. now because of AES decryption it denpends on openssl.
and the size can be make smaller if we don't need support some file format, compiling ffmpeg with --disable-xxx.

Q3) How many windows and android versions supported by fanplayer (e.g win 7 --x and Android 5--X etc) ?
I tested player-win32 work fine on winxp - win10, and player-android work fine on android 4.4 - android 10

Q4) Is possible make dynamic-link-library compatible both with x86 and x64 bit Operating systems ?
yes it is possible.

**Comment by footballs** [comment]
Sent $10. Cheers!
https://www.blockchain.com/btc/tx/1d5f27292b1ccb70eec1905bd977559fe55293024262a8e6f3806119e3b232bc

> binary file can be small, because fanplayer does not denpend on too many third party libraries, only ffmpeg, sound touch, pthread. now because of AES decryption it denpends on openssl.
> and the size can be make smaller if we don't need support some file format, compiling ffmpeg with --disable-xxx, can make ffmpeg library files smaller.

Yeah I know about 3rd party libs. No problem for that. 
But **fanplayer.exe** at  **Fanplayer-Binary** was only 300 kb's.
And I noticed that even an **simple fanplayer build** without **encryption** generates 9000kb of **fanplayer.exe** in my pc.
Which setting's helps you to achieve this 300kb filesize ?


> Q3) How many windows and android versions supported by fanplayer (e.g win 7 --x and Android 5--X etc) ?
> I tested player-win32 work fine on winxp - win10, and player-android work fine on android 4.4 - android 10

very impressive +1

**Comment by rockcarry** [comment]
you mean binrary files build from source code  by yourself is larger than me ？
I don't know why, but may it is because I build it with vs2005 on winxp.
if you have this enviroment you can try it.

**Comment by footballs** [comment]
> 
> 
> you mean binrary files build from source code by yourself is larger than me ？

Yes fanplayer.dll fine but testplayer.exe is 9 mb
> I don't know why, but may it is because I build it with vs2005 on winxp.
> if you have this enviroment you can try it.

Ho ! so you use XP ? I am big fan of it. I will use it again to build. Thanks.
Nevermind, Take care, Keep working and smiling.
Bye :1st_place_medal: 
:)

**Comment by rockcarry** [comment]
I think the root cause is testplayer.exe using MFC as static library.
you can try to change it in project settings:
Use MFC in a Static Library -> Use MFC in a Shared DLL

**Comment by footballs** [comment]
OMG !
**Use MFC in a Shared DLL** and **/md** switch worked.
Now its lower than even your binary. :)
testplayer.exe is now 200 kb only.
Keep it up. I will have more projects for you in future.
