### ISSUE TITLE
Windows和Ubuntu编译问题

### ISSUE THREAD

**Issue by mayingqiao** [rockcarry/fanplayer#39]
在Windows上无法编译，提示gcc不能创建可执行文件（引起原因是build**.sh中把ndk写死为32位路径）。cygwin无法编译成功，改了64位ndk路径也无法编译成功。

在Ubuntu上，build**.sh也是相同提示，需要更改里面CROSS_COMPILE=$NDK_HOME/toolchains/arm-linux-androideabi-4.9/prebuilt/windows/bin/arm-linux-androideabi-   为Linux的路径，否则不能正常编译

**Comment by tanqinghai** [comment]
具体可以查看我的博客https://blog.csdn.net/Dreamhai/article/details/110205922
