### ISSUE TITLE
Recording to a local .mp4 video file on Android

### ISSUE THREAD

**Issue by ggschelling** [rockcarry/fanplayer#4]
Will recording (mp4, on Android) be an issue for an upcoming release?

The performance of your player is great! (y)

**Comment by rockcarry** [comment]
you mean on android platform, you want to record live stream to mp4 file by fanplayer ?

**Comment by ggschelling** [comment]
@rockcarry Yes, that's right. Will this be an issue for an upcoming release?

**Comment by rockcarry** [comment]
there is already an c interface player_record for recording file.

did you try it ?

**Comment by ggschelling** [comment]
Not yet. Sorry I missed that. Thanks!

**Comment by rockcarry** [comment]
yes.
but you need write jni for java. I think it's not difficult for you.

**Comment by rockcarry** [comment]
the lastest code fix the recording crash issue. sugguest you update code.

**Comment by ggschelling** [comment]
Thx!
