### ISSUE TITLE
如何使用HLS协议？

### ISSUE THREAD

**Issue by ibhabc** [rockcarry/fanplayer#41]
我在回购中进行搜索，发现较早的版本支持HLS。 我已编译并修复了问题，但不确定如何填充HLS参数。
它一直在加载。 请参阅：

```cpp
void CplayerDlg::PlayerReset(PLAYER_INIT_PARAMS *params)
{
    player_close(m_ffPlayer);
	//m_ffPlayer = player_open(m_strUrl, GetSafeHwnd(), params);
	char *url = "http://localhost/sl.m3u8";
	m_ffPlayer = player_open_hls(url,NULL, GetSafeHwnd(), params);
}
```
该文件可以在vlc上正常播放。

**Comment by ibhabc** [comment]
[hls.zip](https://github.com/rockcarry/fanplayer/files/5649132/hls.zip)

**Comment by rockcarry** [comment]
hls 应该是支持的才对啊，你用 fanplayer-binary 编译好的版本测试过没。

**Comment by ibhabc** [comment]
是的，它的演奏很好。 问题可能出在** player_open_hls **中。
** player_open **正在顺利播放hls。 但是我想知道player_open_hls **的目的是什么？

**Comment by rockcarry** [comment]
player_open_hls 这是另外一个分支里面的接口把，是之前给一个网友定制的一个功能，貌似可以传入一个 key 进去。具体什么用我也不记得了。

**Comment by ibhabc** [comment]
对。
好吧，hls可以使用**player_open_hls**正常播放，所以暂时关闭该问题。
谢谢。 您的帮助将被记住。 
🥰 🥰 🥰
