### ISSUE TITLE
linux平台要怎么玩

### ISSUE THREAD

**Issue by FlyLu** [rockcarry/fanplayer#47]
大佬，请问下，linux平台需要自己移植哪几部分

**Comment by rockcarry** [comment]
adev + vdev 就可以了

**Comment by FlyLu** [comment]
没有单独的移植文件吗，提供一套hal层相关抽象的接口

**Comment by FlyLu** [comment]
我有一个嵌入式的带屏幕的板子，想搞一套音视频的播放器

**Comment by rockcarry** [comment]
嵌入式 linux 要自己做移植，ffmpeg 的 avdevices 里面有 fbdev ，应该是 framebuffer 设备，可以试下是否直接能用。
