### ISSUE TITLE
安卓版本编译不过

### ISSUE THREAD

**Issue by HelloTodayWolrd** [rockcarry/fanplayer#51]
>sh .\build_fanplayer_jni.sh arm
HEAD is now at fd78df59b0 Prepare for 1.1.1k release
Configuring OpenSSL version 1.1.1k (0x101010bfL) for android-arm
Using os-specific seed configuration
no NDK arm-linux-androideabi-gcc on $PATH at (eval 7) line 124.

编译安卓版本的时候，无论怎么配置都是报上面错误，貌似是执行
命令行：./Configure no-shared $OPENSSL_TARGET -D__ANDROID_API__=21 --prefix=$PREFIX_DIR 这一步的时候报的错误
搞了好久没有编译通过，请教大神指点迷津了

**Comment by rockcarry** [comment]
请打开 build_fanplayer_jni.sh 这个文件，阅读里面的说明
你应该是没有 export ANDROID_NDK_HOME 这环境变量

**Comment by HelloTodayWolrd** [comment]
在msys下编译的，ANDROID_NDK_HOME 已经设置了，改成在ubuntu环境下编译，编译通过
