### ISSUE TITLE
Couple seconds delay when playing tcp stream

### ISSUE THREAD

**Issue by DanielKow** [rockcarry/fanplayer#72]
I have an h264 stream. The player reads it and plays it without noticeable delay (about 200ms) when we send it by RTSP. 
There is a problem when I'm passing TCP URL directly. I have a couple of seconds of delay (more than 5). The stream is the same. I tried changing the profile and level of my h264 stream but it did not help.
Why is there no delay when I send the stream into RTSP and there is a couple of seconds of latency when I open TCP directly?
I'm working on Android.

**Comment by rockcarry** [comment]
try change player parameter avts_syncmode

**Comment by DanielKow** [comment]
Thanks for your response.
After changing avts_syncmode parameter delay was smaller, but still, it is 2 or 3 seconds.
I have noticed an interesting thing after 4-6 minutes of streaming delay was reduced to 200ms.
There is any buffer implemented in your player?
In ffplay I can use -fflags nobuffer and -flags low_delay to achieve video without noticeable delay.
Are there similar options in fanplayer?

**Comment by rockcarry** [comment]
try:
avts_syncmode = 3;
video_bufpktn = 0;
video_frame_rate = ?; // set to actual frame rate

**Comment by DanielKow** [comment]
This combination of parameters worked like a charm. Thank you very much :)
